image:
  name: maven:3.8.3-jdk-8
  entrypoint: ["/bin/sh","-c"]

before_scripts:
  stage: .pre
  script:
    - mvn -v

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - mvn clean
    - mvn install

deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "hello deploy"