stages:
  - build
  - deploy

build:
  stage: build
  only:
  - master
  script:
    - echo "mvn clean"
    - echo "mvn install"

deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "hello deploy"