stages:
  - build
  - test
  - deploy

module-a-build:
  stage: build
  script:
    - echo "hello3a"
    - sleep 10

module-b-build:
  stage: build
  script:
    - echo "hell3b"
    - sleep 20

module-a-test:
  stage: test
  script:
    - echo "hello3a"
    - sleep 5
  needs: ["module-a-build"]
module-b-test:
  stage: test
  script:
    - echo "hello3b"
    - sleep 5
  needs: ["module-b-build"]